/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.table.DefaultTableModel;
import model.bean.Medico;
import model.dao.MedicoDAO;

/**
 *
 * @author K_programmer
 */
public class TelaMedicos extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaMedicos() {
        initComponents();
        //listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void listar(){
       DefaultTableModel modelo= (DefaultTableModel) medics.getModel();
        MedicoDAO mdao= new MedicoDAO();
       
        modelo.setNumRows(0);
       for (Medico m : mdao.Lista()) {
           
           modelo.addRow(new Object[]{
                m.getCod(),
             m.getNome(),
             m.getBi(),
           m.getMorada()
         
           
           });
         
           
       }
   }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        medics = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        morada = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 0, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Apagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 130, 40));

        jButton2.setBackground(new java.awt.Color(51, 0, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 40));

        medics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "BI", "Morada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        medics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                medicsMouseReleased(evt);
            }
        });
        medics.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                medicsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(medics);
        if (medics.getColumnModel().getColumnCount() > 0) {
            medics.getColumnModel().getColumn(0).setResizable(false);
            medics.getColumnModel().getColumn(1).setResizable(false);
            medics.getColumnModel().getColumn(2).setResizable(false);
            medics.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 400, 380));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 70, 30));

        nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nome.setForeground(new java.awt.Color(51, 0, 153));
        nome.setBorder(null);
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 250, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("BI:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 70, 30));

        bi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bi.setForeground(new java.awt.Color(51, 0, 153));
        bi.setBorder(null);
        jPanel1.add(bi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 250, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Morada:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 70, 20));

        morada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        morada.setForeground(new java.awt.Color(51, 0, 153));
        morada.setBorder(null);
        jPanel1.add(morada, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 250, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bg.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Medico m=new Medico();
       MedicoDAO mDao=new MedicoDAO();
       m.setCod(Integer.parseInt(medics.getValueAt(medics.getSelectedRow(), 0).toString()));
       m.setNome(nome.getText());
       m.setBi(bi.getText());
       m.setMorada(morada.getText());
       
       mDao.update(m);
      
       
       nome.setText("");
       bi.setText("");
       morada.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void medicsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medicsKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_medicsKeyReleased

    private void medicsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicsMouseReleased
        try {
             System.err.println(medics.getValueAt(medics.getSelectedRow(), 0).toString());
       nome.setText(medics.getValueAt(medics.getSelectedRow(), 1).toString());
       bi.setText(medics.getValueAt(medics.getSelectedRow(), 2).toString());
       morada.setText(medics.getValueAt(medics.getSelectedRow(), 3).toString());  
       
         
        } catch (Exception e) {
        }
       
       
    }//GEN-LAST:event_medicsMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMedicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medics;
    private javax.swing.JTextField morada;
    private javax.swing.JTextField nome;
    // End of variables declaration//GEN-END:variables
}
